apiVersion: v1
kind: Service
metadata: 
    name: nextjsservice
    labels: {{ .Values.appLabel }}
spec: 
   type: NodePort
   selector: 
      labels: {{ .Values.appLabel }}
   ports: 
      - containerPort: {{ .Values.appPort }}
        targetPort: {{ .Values.appPort }}
        nodePort: {{ .Values.nodePort }}